// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfxlqnlkpyruyvrbjwew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmeGxxbmxrcHlydXl2cmJqd2V3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNjM1ODMsImV4cCI6MjA2NzkzOTU4M30.yV8BFDKmqn0-auDfTGfADQ2I_4Sq_4pEUMlfufRTKbs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});